
package com.log10x.ext.cloud.index.util;

import java.io.IOException;
import java.io.Reader;
import java.util.List;

/**
*  Utility Reader wrapper of List<String> separated by line breaks.
*  Generated by co-pilot, prompt:
*  generate a java reader sub class that reads characters from a list of strings 
*  where items in the list are separated by the system line separator
*/
public class StringListReader extends Reader {
    private final List<String> strings;
    private int currentStringIndex;
    private int currentCharIndex;
    private final String lineSeparator;
    private boolean lineSeparatorRead;

    public StringListReader(List<String> strings) {
        this.strings = strings;
        this.currentStringIndex = 0;
        this.currentCharIndex = 0;
        this.lineSeparator = System.lineSeparator();
        this.lineSeparatorRead = false;
    }

    @Override
    public int read(char[] cbuf, int off, int length) throws IOException {
       
    	if (currentStringIndex >= strings.size() && lineSeparatorRead) {
            return -1; // End of stream
        }
    	
    	int len = length;

        int charsRead = 0;
        while (len > 0 && (currentStringIndex < strings.size() || !lineSeparatorRead)) {
            if (currentCharIndex >= strings.get(currentStringIndex).length()) {
                if (!lineSeparatorRead) {
                    int charsToRead = Math.min(lineSeparator.length(), len);
                    lineSeparator.getChars(0, charsToRead, cbuf, off + charsRead);
                    charsRead += charsToRead;
                    len -= charsToRead;
                    lineSeparatorRead = true;
                } else {
                    currentStringIndex++;
                    currentCharIndex = 0;
                    lineSeparatorRead = false;
                }
            } else {
                String currentString = strings.get(currentStringIndex);
                int charsToRead = Math.min(currentString.length() - currentCharIndex, len);
                currentString.getChars(currentCharIndex, currentCharIndex + charsToRead, cbuf, off + charsRead);
                charsRead += charsToRead;
                currentCharIndex += charsToRead;
                len -= charsToRead;
            }
        }

        return charsRead > 0 ? charsRead : -1;
    }

    @Override
    public void close() throws IOException {
        // No resources to close in this implementation
    }

    public static void main(String[] args) {
        List<String> strings = List.of("Hello", "World", "This", "Is", "A", "Test");
        try (StringListReader reader = new StringListReader(strings)) {
            char[] buffer = new char[1024];
            int n;
            while ((n = reader.read(buffer)) != -1) {
                System.out.print(new String(buffer, 0, n));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
